"""Inspect the BDNS / SNPSAP OpenAPI document.

Goal
----
Confirm the real REST surface of BDNS before relying on it in runtime.
This script:

1. Loads an OpenAPI document either from a local file (recommended for
   offline runs) or by fetching the configured ``BDNS_SWAGGER_URL`` /
   any URL passed on the command line.
2. Lists every path declared in the document.
3. Flags paths that look related to "convocatorias" so the maintainer
   can spot the canonical search endpoint.
4. Writes a snapshot under ``docs/bdns_openapi_snapshot.md`` so future
   diffs against BDNS are visible in version control.

The script does not modify ``BDNS_API_BASE_URL`` or
``BDNSService``. Updating the path is a manual decision, taken after
reading the snapshot.

Usage
-----
.. code-block:: bash

    # Offline (uses bundled fixture)
    python scripts/inspect_bdns_swagger.py --source tests/fixtures/bdns_swagger_sample.json

    # Online (uses configured swagger URL)
    python scripts/inspect_bdns_swagger.py --online
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "bdns_swagger_sample.json"
DEFAULT_SNAPSHOT = REPO_ROOT / "docs" / "bdns_openapi_snapshot.md"

KEYWORDS_OF_INTEREST = (
    "convocator",
    "ayud",
    "subvenc",
    "concesion",
    "beneficiar",
)


@dataclass(frozen=True)
class PathSummary:
    path: str
    methods: tuple[str, ...]
    summary: str | None
    looks_like_convocatorias_search: bool


def _load_document(*, source: Path | None, online_url: str | None) -> dict[str, Any]:
    if source is not None:
        try:
            return json.loads(source.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise SystemExit(f"BDNS swagger file not found: {source}") from exc
        except json.JSONDecodeError as exc:
            raise SystemExit(
                f"BDNS swagger file is not valid JSON: {source} ({exc})"
            ) from exc
    if online_url is None:
        raise SystemExit("Either --source or --online must be provided.")
    try:
        response = httpx.get(online_url, timeout=30.0)
    except httpx.HTTPError as exc:
        raise SystemExit(f"Failed to fetch swagger from {online_url}: {exc}") from exc
    if response.status_code >= 400:
        raise SystemExit(
            f"BDNS swagger fetch returned {response.status_code}: {response.text[:200]}"
        )
    try:
        return response.json()
    except ValueError as exc:
        raise SystemExit(
            f"Swagger fetch did not return JSON: {response.text[:200]}"
        ) from exc


def _path_methods(path_item: dict[str, Any]) -> tuple[str, ...]:
    http_methods = {"get", "post", "put", "delete", "patch", "options", "head"}
    return tuple(
        method.upper() for method in path_item if method.lower() in http_methods
    )


def _path_summary(path: str, path_item: dict[str, Any]) -> str | None:
    for method_data in path_item.values():
        if isinstance(method_data, dict):
            summary = method_data.get("summary") or method_data.get("description")
            if isinstance(summary, str) and summary.strip():
                return summary.strip()
    return None


def _is_candidate_for_search(path: str, summary: str | None) -> bool:
    haystack = f"{path} {summary or ''}".lower()
    return any(keyword in haystack for keyword in KEYWORDS_OF_INTEREST)


def summarize_paths(document: dict[str, Any]) -> list[PathSummary]:
    paths_block = document.get("paths") or {}
    if not isinstance(paths_block, dict):
        raise SystemExit("Swagger document does not contain a 'paths' object.")
    summaries: list[PathSummary] = []
    for path, path_item in sorted(paths_block.items()):
        if not isinstance(path_item, dict):
            continue
        methods = _path_methods(path_item)
        summary = _path_summary(path, path_item)
        summaries.append(
            PathSummary(
                path=path,
                methods=methods,
                summary=summary,
                looks_like_convocatorias_search=_is_candidate_for_search(path, summary),
            )
        )
    return summaries


def render_snapshot(
    summaries: Iterable[PathSummary],
    *,
    source_label: str,
) -> str:
    lines: list[str] = [
        "# BDNS OpenAPI snapshot",
        "",
        f"Source: `{source_label}`",
        "",
        "This snapshot is generated by `scripts/inspect_bdns_swagger.py`. ",
        "It is informational. Do not edit by hand.",
        "",
        "## All declared paths",
        "",
        "| Path | Methods | Summary |",
        "| --- | --- | --- |",
    ]
    summaries = list(summaries)
    for item in summaries:
        methods = ", ".join(item.methods) or "-"
        summary = (item.summary or "").replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{item.path}` | {methods} | {summary} |")
    lines.append("")
    lines.append("## Candidate search endpoints (heuristic)")
    lines.append("")
    candidates = [item for item in summaries if item.looks_like_convocatorias_search]
    if not candidates:
        lines.append("_No path matched the convocatoria-related keywords._")
    else:
        for item in candidates:
            methods = ", ".join(item.methods) or "-"
            summary = item.summary or "(no summary)"
            lines.append(f"- `{item.path}` ({methods}) — {summary}")
    lines.append("")
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Inspect the BDNS OpenAPI document.")
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_FIXTURE,
        help="Path to a local OpenAPI JSON file (default: bundled fixture).",
    )
    parser.add_argument(
        "--online",
        action="store_true",
        help="Fetch the swagger from BDNS_SWAGGER_URL instead of reading --source.",
    )
    parser.add_argument(
        "--snapshot",
        type=Path,
        default=DEFAULT_SNAPSHOT,
        help="Where to write the markdown snapshot.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.online:
        from app.core.config import get_settings

        url = get_settings().bdns_swagger_url
        document = _load_document(source=None, online_url=url)
        source_label = url
    else:
        document = _load_document(source=args.source, online_url=None)
        source_label = str(args.source.relative_to(REPO_ROOT))

    summaries = summarize_paths(document)
    snapshot = render_snapshot(summaries, source_label=source_label)
    args.snapshot.parent.mkdir(parents=True, exist_ok=True)
    args.snapshot.write_text(snapshot, encoding="utf-8")

    candidates = [s for s in summaries if s.looks_like_convocatorias_search]
    print(f"Inspected {len(summaries)} paths from {source_label}.")
    try:
        snapshot_label = str(args.snapshot.relative_to(REPO_ROOT))
    except ValueError:
        snapshot_label = str(args.snapshot)
    print(f"Snapshot written to {snapshot_label}.")
    if candidates:
        print("Candidate convocatoria endpoints:")
        for item in candidates:
            print(f"  - {item.path} ({', '.join(item.methods) or '-'})")
    else:
        print("No candidate convocatoria endpoints found.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
